// Called by github actions to verify the code generated by the cli
const assert = require('assert/strict');
const { generatedRegexMatcher } = require('./test.js');

const result = generatedRegexMatcher('abc');
assert.deepEqual(result, { index: 0, matches: ['abc'] });
